---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: beta-app
  labels:
    app.kubernetes.io/name: account-service
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: account-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: account-service
    spec:
      containers:
        - name: account-service-api
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/account-service:635a29b
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8089
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: HOST_DB
              value: postgres-service.db-system
            - name: HOST_CONFIG
              value: config-server
            - name: HOST_REGISTRY
              value: service-registry
