---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: beta-app
spec:
  type: ClusterIP
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app.kubernetes.io/name: account-service